# Generated by Django 3.0.8 on 2020-08-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='desc',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
