# Generated by Django 3.0.8 on 2020-08-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_portfolio_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='address',
            new_name='location',
        ),
    ]
