# Generated by Django 3.0.8 on 2020-08-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200803_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/pics'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='location',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
