# Generated by Django 3.0.8 on 2020-08-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200805_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True, max_length=250)),
                ('desc', models.TextField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
